package net.novauniverse.bedwars.game.enums;

public enum Reason {
    PICKAXE_UPGRADE,AXE_UPGRADE,NORMAL_ITEM_BOUGHT,ARMOR_BOUGHT, NOT_ENOUGH_SPACE, ALREADY_HAS_ARMOR, ALREADY_HAS_HIGHER_TIER_ARMOR, ALREADY_HAS_PICKAXE_MAX_TIER, ALREADY_HAS_AXE_MAX_TIER, NOT_ENOUGHT_MATERIALS
}
